comment:
  layout: 'header, diff, flags, files,  components'
  behavior: default # Add a comment on every PR with updated coverage
  require_changes: false # Always show comment, even if no coverage change

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - '!main'
  individual_components:
    - component_id: theme
      name: Theme
      paths:
        - apps/web/src/theme/**
    - component_id: schema
      name: schema
      paths:
        - packages/schema/**
    - component_id: eslint-config
      name: eslint-config
      paths:
        - packages/eslint-config/**
    - component_id: vite-plugin-msw-server
      name: vite-plugin-msw-server
      paths:
        - packages/vite-plugin-msw-server/**
    - component_id: vite-plugin-sitemap
      name: vite-plugin-sitemap
      paths:
        - packages/vite-plugin-sitemap/**
    - component_id: vite-plugin-watch
      name: vite-plugin-watch
      paths:
        - packages/vite-plugin-watch/**
    - component_id: api
      name: api
      paths:
        - workers/api/**
