/**
 * Codegen for the Experience network graph.
 *
 * Runs `buildGraph` over the authored `techNodes` once, at build time, and writes
 * the result as a typed module (`ExperienceGraph.data.generated.ts`). The app then
 * imports that literal directly, so neither `buildGraph` nor the authoring data ship
 * in the client bundle and there is no runtime graph-construction cost.
 *
 * Run with: `pnpm gen:experienceGraph` (re-run after editing ExperienceGraph.data.ts).
 * The `ExperienceGraph.data.generated.test.ts` drift guard fails if it goes stale.
 */
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

// Dynamic imports with explicit .ts so node's native TS runner can resolve them.
// (A static `import … from '….ts'` is rejected by the repo's no-restricted-syntax
// lint rule, which only matches static import declarations — not import() calls.)
const { ROOT_ID, techNodes } =
  await import('../src/section/ExperienceGraph/ExperienceGraph.data.ts')
const { buildGraph } = await import('../src/section/ExperienceGraph/utils/buildGraph.ts')

const here = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(here, '../src/section/ExperienceGraph/ExperienceGraph.data.generated.ts')

const data = { rootId: ROOT_ID, ...buildGraph(techNodes, ROOT_ID) }

const j = (value: unknown) => JSON.stringify(value)
const mapLiteral = (map: Map<string, unknown>) => {
  const entries = [...map.entries()].map(([k, v]) => `[${j(k)}, ${j(v)}]`)
  return `new Map([${entries.join(', ')}])`
}

const source = `
// AUTO-GENERATED by scripts/gen-experienceGraph.ts — do not edit by hand.
// Regenerate with \`pnpm gen:experienceGraph\`
// Watch on pnpm dev after editing ExperienceGraph.data.ts to regenerate on every change.
import type { GraphData } from 'src/common/NetworkGraph'

export const experienceGraphData: GraphData = {
  rootId: ${j(data.rootId)},
  nodes: ${j(data.nodes)},
  links: ${j(data.links)},
  branchIds: new Set(${j([...data.branchIds])}),
  topLevelIds: ${j(data.topLevelIds)},
  childrenByParent: ${mapLiteral(data.childrenByParent)},
  titleById: ${mapLiteral(data.titleById)},
  optionalIds: new Set(${j([...data.optionalIds])}),
  featuredIds: new Set(${j([...data.featuredIds])}),
  relationAnchoredIds: new Set(${j([...data.relationAnchoredIds])}),
  areasByNode: ${mapLiteral(data.areasByNode)},
}
`

const prettierOptions = await resolveConfig(outFile)
const formatted = await format(source, { ...prettierOptions, parser: 'typescript' })

writeFileSync(outFile, formatted)
