import { createContext } from 'react'
import { type Theme } from '@emotion/react'

/** Per-field state, middle priority in the override chain (overrides Form, overridden by explicit props). */
export interface FormControlContextValue {
  /** Field id — links FormLabel `htmlFor` and the control. Auto-generated by FormControl when not provided. */
  id: string
  /** Id of the helper/error text node, used for `aria-describedby`. */
  helperId: string
  error?: boolean
  disabled?: boolean
  required?: boolean
  size?: keyof Theme['sizes']
  fullWidth?: boolean
  color?: keyof Theme['palette']
  /** Text color for label/helper/input content — resolves against `theme.text`. */
  textColor?: keyof Theme['text']
  /** Whether a FormHelperText is currently rendered — drives `aria-describedby` on the control. */
  hasHelperText: boolean
  /** Stable setter FormHelperText calls to register/unregister its presence. */
  setHasHelperText: (present: boolean) => void
}

export const FormControlContext = createContext<FormControlContextValue | null>(null)
