blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/soroush-tech/soroush.tech/discussions
    about: Please use Discussions for questions, ideas, or general feedback.
  - name: Documentation
    url: https://soroush.tech/storybook
    about: Check the docs before opening an issue.
