export const ROOT_ID = 'EXPERIENCE'

/** Areas — the show/hide toggles and the top level (there is no root node). Stable
 *  short ids; label in `title`. */
export const A = {
  WEB: '0',
  MOBILE: '1',
  DESKTOP: '2',
  BACK_END: '3',
  DESIGN: '4',
  LANGUAGE: '5',
} as const

/** Groups — drawn label-nodes; each links to its members and rides along when a
 *  member is visible. */
export const G = {
  BUILD_TOOLS: '21',
  PERFORMANCE: '22',
  DATABASE: '23',
  CI_CD: '24',
  STORAGE: '25',
  TEST_UNIT: '26',
  TEST_E2E: '28',
  SECURITY: '27',
  API_INTEGRATIONS: '29',
  STATE_MANAGEMENT: '30',
  VALIDATION: '31',
  ORM: '32',
  DATA_STREAM: '33',
  DATA_FETCHING: '34',
  STYLE: '35',
  QUEUES: '36',
  AI: '37',
  LIB_FRA: '38',
  DATA_PRESENTATION: '39',
} as const

/** Nodes — tech used as a `parent` (sub-tech nests under it) or a relation target,
 *  so they need a stable id. Plain leaves keep a readable string id. */
export const N = {
  NODE_JS: '100',
  REACT: '101',
  REACT_NATIVE: '102',
  ELECTRON: '103',
  NEXT_JS: '104',
  VITE: '105',
  WEBPACK: '106',
  REDUX: '107',
  POSTGRES: '108',
  ANGULAR_JS: '109',
  EMBER: '110',
  EXT_JS: '111',
  BACKBONE: '112',
  NEST_JS: '113',
  JQUERY: '114',
  PREACT: '115',
  SOLID_JS: '116',
  REMIX: '117',
  FASTIFY: '118',
  EXPRESS: '119',
  TOTAL_JS: '120',
  LOOPBACK: '121',
  CORDOVA: '122',
  IONIC: '123',
  Lottie: '124',
  JEST: '125',
  VITEST: '126',
  EXTJS: '127',
  JENKINS: '128',
  BUILD_BOT: '129',
  MONGO: '130',
  TS: '131',
  TAN_STACK: '132',
  GRAPHQL: '133',
  REST: '134',
  RPC: '135',
  GRPC: '136',
  SOAP: '137',
  CSS: '138',
  PHP: '139',
  JS: '140',
  RUST: '141',
  HTML: '142',
  WASM: '143',
  TAURI: '144',
  ELECTRON_BUILDER: '145',
  ELECTRON_FORGE: '146',
  WS: '147',
  BABEL: '148',
  MSW: '149',
  PLAYWRIGHT: '150',
  PROFILING: '151',
  UX: '152',
  TEST: '153',
  YII2: '154',
} as const

export type Area = (typeof A)[keyof typeof A]
export type Group = (typeof G)[keyof typeof G]
export type Node = (typeof N)[keyof typeof N]

export interface TechNode {
  /** Globally unique key (every edge/lookup/d3-join uses it). Defaults the title. */
  id: string
  /** Display label. Defaults to `id`. */
  title?: string
  /** Node radius. Defaults by role: area 25, group 18, node 10. */
  size?: number
  /** Level: `area` (top-level toggle), `group` (a drawn label node), or `node` (tech). */
  kind: 'area' | 'group' | 'node'
  /** Area tags — gate show/hide only, no line drawn. Own tags override those inherited
   *  from parents; with none, the node follows its parents' tags. */
  area?: Area[]
  /** Parent attachments — the drawn containment line. A parent may be a node (e.g. Redux
   *  under React), an area (Web ← React), or `ROOT_ID` (an area off the central root). The
   *  node's gate flows in from its parents unless it sets its own `area`. */
  parent?: (Area | Node | typeof ROOT_ID)[]
  /** Categorical label nodes (a group, or a node acting as one) — dotted group line. */
  groups?: (Group | Node)[]
  /** Lateral associations to other nodes (e.g. React ↔ React Native). Dashed threads. */
  relations?: (Area | Node)[]
  /** Optional/legacy tech — collected so the legend can offer a show/hide toggle. */
  legacy?: boolean
  /** Auto-expand one level: when its area opens, this node's direct children show too
   *  without a click (still collapsible). E.g. React ⇒ Zustand/Redux ride along. */
  featured?: boolean
}

// ── Edit only this ─────────────────────────────────────────────────────────────
// After editing, regenerate the render graph: `pnpm gen:experienceGraph`.
// Strict: a duplicate id, unknown/wrong-kind reference, a node with no area/parent, or
// a node unreachable from an area throws at gen time.

export const techNodes: TechNode[] = [
  // ── Areas (attached to the central root) ──
  { id: A.DESIGN, title: 'Design', kind: 'area', parent: [ROOT_ID] },
  { id: A.WEB, title: 'Web', kind: 'area', parent: [ROOT_ID] },
  { id: A.MOBILE, title: 'Mobile', kind: 'area', parent: [ROOT_ID] },
  { id: A.DESKTOP, title: 'Desktop', kind: 'area', parent: [ROOT_ID] },
  { id: A.BACK_END, title: 'Back-end', kind: 'area', parent: [ROOT_ID] },
  { id: A.LANGUAGE, title: 'Language', kind: 'area', parent: [ROOT_ID] },

  // ── Groups (drawn label nodes) ──

  { id: G.BUILD_TOOLS, title: 'Build Tools', kind: 'group' },
  { id: G.PERFORMANCE, title: 'Performance', kind: 'group' },
  { id: G.DATABASE, title: 'Database', kind: 'group' },
  { id: G.CI_CD, title: 'CI/CD', kind: 'group' },
  { id: G.STORAGE, title: 'Storage', kind: 'group' },
  { id: G.TEST_UNIT, title: 'Testing', kind: 'group' },
  { id: G.TEST_E2E, title: 'E2E Testing', kind: 'group' },
  { id: G.SECURITY, title: 'Security', kind: 'group' },
  { id: G.API_INTEGRATIONS, title: 'API Integrations', kind: 'group' },
  { id: G.STATE_MANAGEMENT, title: 'State Management', kind: 'group' },
  { id: G.VALIDATION, title: 'Validation', kind: 'group' },
  { id: G.ORM, title: 'ORM', kind: 'group' },
  { id: G.DATA_STREAM, title: 'Data Streaming', kind: 'group' },
  { id: G.DATA_FETCHING, title: 'Data Fetching', kind: 'group' },
  { id: G.STYLE, title: 'Style', kind: 'group' },
  { id: G.QUEUES, title: 'Queues', kind: 'group' },
  { id: G.LIB_FRA, title: 'Libraries/Frameworks', kind: 'group' },
  { id: G.DATA_PRESENTATION, title: 'Data Presentation', kind: 'group' },

  // ── Language (JS/TS reach Back-end through Node.js) ──
  {
    id: N.TS,
    title: 'TypeScript',
    kind: 'node',
    size: 18,
    relations: [N.NODE_JS, N.REACT_NATIVE, N.REACT, N.ELECTRON],
    parent: [A.LANGUAGE],
  },
  {
    id: N.JS,
    title: 'JavaScript',
    kind: 'node',
    size: 18,
    relations: [
      N.NODE_JS,
      N.REACT_NATIVE,
      N.REACT,
      N.EXT_JS,
      N.CORDOVA,
      N.ELECTRON,
      N.ANGULAR_JS,
      N.JQUERY,
      N.REMIX,
    ],
    parent: [A.LANGUAGE],
  },
  {
    id: N.RUST,
    title: 'Rust',
    kind: 'node',
    size: 18,
    relations: [N.REACT, N.WASM, N.TAURI],
    parent: [A.LANGUAGE],
  },
  {
    id: N.PHP,
    title: 'PHP',
    kind: 'node',
    size: 18,
    parent: [A.LANGUAGE],
    legacy: true,
  },
  {
    id: N.HTML,
    title: 'HTML5',
    kind: 'node',
    parent: [A.LANGUAGE],
  },
  {
    id: N.CSS,
    title: 'CSS3',
    kind: 'node',
    parent: [A.LANGUAGE],
  },
  {
    id: N.WASM,
    title: 'WebAssembly',
    kind: 'node',
    relations: [A.WEB],
    parent: [A.LANGUAGE],
  },
  {
    id: N.UX,
    title: 'UX Optimization',
    kind: 'node',
    area: [A.WEB],
    parent: [N.REACT, N.REACT_NATIVE],
  },
  {
    id: N.PROFILING,
    title: 'Profiling',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [A.WEB],
  },

  // ── Anchor nodes (parents / relation targets for other tech) ──
  {
    id: N.NODE_JS,
    title: 'Node.js',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [A.BACK_END],
    groups: [G.LIB_FRA],
  },

  // Libraries / Frameworks
  {
    id: N.REACT_NATIVE,
    title: 'React Native',
    kind: 'node',
    size: 15,
    area: [A.MOBILE],
    parent: [A.MOBILE, N.REACT],
    relations: [],
    groups: [G.LIB_FRA],
    featured: true,
  },
  {
    id: N.IONIC,
    title: 'Ionic',
    kind: 'node',
    size: 15,
    area: [A.MOBILE],
    parent: [A.MOBILE],
    relations: [N.ANGULAR_JS],
    groups: [G.LIB_FRA],
    legacy: true,
  },

  {
    id: N.CORDOVA,
    title: 'Apache Cordova',
    kind: 'node',
    area: [A.MOBILE],
    parent: [A.MOBILE],
    relations: [N.EXT_JS],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.ELECTRON,
    title: 'Electron',
    kind: 'node',
    size: 15,
    area: [A.DESKTOP],
    parent: [A.DESKTOP],
    groups: [G.LIB_FRA],
    relations: [N.REACT, N.NODE_JS, N.ELECTRON_BUILDER, N.ELECTRON_FORGE],
    featured: true,
  },
  {
    id: N.TAURI,
    title: 'Tauri',
    kind: 'node',
    size: 15,
    area: [A.DESKTOP],
    parent: [A.DESKTOP],
    groups: [G.LIB_FRA],
    relations: [N.RUST],
  },
  {
    id: N.EXTJS,
    title: 'ExtJS',
    kind: 'node',
    area: [A.MOBILE, A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
    size: 15,
  },
  {
    id: N.BACKBONE,
    title: 'Backbone',
    kind: 'node',
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.NEXT_JS,
    title: 'Next.js',
    kind: 'node',
    size: 15,
    relations: [N.REACT],
    area: [A.WEB, A.BACK_END],
    groups: [G.LIB_FRA],
    parent: [A.WEB, N.NODE_JS],
    featured: true,
  },
  {
    id: N.TOTAL_JS,
    title: 'Total.js',
    kind: 'node',
    size: 15,
    relations: [N.NODE_JS],
    area: [A.BACK_END],
    groups: [G.LIB_FRA],
    parent: [N.NODE_JS],
    featured: true,
  },
  {
    id: N.REACT,
    title: 'React',
    kind: 'node',
    size: 15,
    area: [A.WEB, A.MOBILE],
    parent: [A.WEB, A.MOBILE],
    relations: [N.REACT_NATIVE, N.ELECTRON],
    groups: [G.LIB_FRA],
    featured: true,
  },
  {
    id: N.ANGULAR_JS,
    title: 'AngularJS',
    kind: 'node',
    size: 15,
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.EXT_JS,
    title: 'Ext JS',
    kind: 'node',
    area: [A.WEB, A.MOBILE],
    parent: [A.WEB, N.CORDOVA],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.JQUERY,
    title: 'jQuery',
    kind: 'node',
    size: 15,
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.REMIX,
    title: 'Remix',
    kind: 'node',
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.SOLID_JS,
    title: 'SolidJS',
    kind: 'node',
    size: 15,
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.FASTIFY,
    title: 'Fastify',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [N.NODE_JS],
    groups: [G.LIB_FRA],
    featured: true,
  },
  {
    id: N.EXPRESS,
    title: 'Express',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [N.NODE_JS],
    groups: [G.LIB_FRA],
  },
  {
    id: N.LOOPBACK,
    title: 'LoopBack',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [N.NODE_JS],
    groups: [G.LIB_FRA],
    legacy: true,
  },
  {
    id: N.NEST_JS,
    title: 'NestJS',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [N.NODE_JS],
    groups: [G.LIB_FRA],
    featured: true,
  },
  {
    id: N.YII2,
    title: 'Yii v2',
    kind: 'node',
    size: 15,
    area: [A.BACK_END],
    parent: [N.PHP],
    groups: [G.LIB_FRA],
    featured: true,
  },

  // Build tols
  {
    id: N.VITE,
    title: 'Vite',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [A.WEB],
    relations: [N.REACT_NATIVE, N.REACT, N.TS],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: N.ELECTRON_BUILDER,
    title: 'electron-builder',
    kind: 'node',
    size: 12,
    area: [A.DESKTOP],
    parent: [N.ELECTRON],
    relations: [N.REACT, N.JENKINS],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: N.ELECTRON_FORGE,
    title: 'Electron Forge',
    kind: 'node',
    size: 12,
    area: [A.DESKTOP],
    parent: [N.ELECTRON],
    relations: [N.REACT, N.BUILD_BOT],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: N.WEBPACK,
    title: 'Webpack',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [N.REACT, N.BABEL],
    groups: [G.BUILD_TOOLS],
    legacy: true,
  },

  // STATE_MANAGEMENT
  {
    id: N.REDUX,
    title: 'Redux',
    kind: 'node',
    size: 12,
    parent: [N.REACT, N.REACT_NATIVE],
    groups: [G.STATE_MANAGEMENT],
  },
  {
    id: 'Redux Toolkit',
    size: 15,
    kind: 'node',
    parent: [N.REDUX],
    relations: [N.REST, N.MSW],
    groups: [G.STATE_MANAGEMENT, G.DATA_FETCHING],
    featured: true,
  },
  { id: 'Redux Saga', kind: 'node', parent: [N.REDUX], groups: [G.STATE_MANAGEMENT] },
  { id: 'Redux Thunk', kind: 'node', parent: [N.REDUX], groups: [G.STATE_MANAGEMENT] },
  { id: 'Redux ORM', kind: 'node', parent: [N.REDUX], legacy: true, groups: [G.STATE_MANAGEMENT] },
  { id: 'Redux Persist', kind: 'node', parent: [N.REDUX], groups: [G.STATE_MANAGEMENT] },
  {
    id: 'Redux Selector',
    kind: 'node',
    parent: [N.REDUX],
    legacy: true,
    groups: [G.STATE_MANAGEMENT],
  },
  { id: 'Zustand', kind: 'node', size: 15, parent: [N.REACT], groups: [G.STATE_MANAGEMENT] },
  { id: 'Jotai', kind: 'node', size: 12, parent: [N.REACT], groups: [G.STATE_MANAGEMENT] },
  { id: 'Context API', kind: 'node', size: 12, parent: [N.REACT], groups: [G.STATE_MANAGEMENT] },
  //

  {
    id: N.TAN_STACK,
    title: 'TanStack',
    kind: 'node',
    parent: [N.REACT, N.NEXT_JS, N.REACT_NATIVE],
    relations: [N.RPC, N.WS],
    featured: true,
  },
  {
    id: 'TanStack/Query',
    kind: 'node',
    parent: [N.TAN_STACK],
    relations: [N.REST, N.GRAPHQL, N.MSW],
    groups: [G.DATA_FETCHING],
  },
  {
    id: 'TanStack/Table',
    kind: 'node',
    parent: [N.TAN_STACK],
    groups: [G.DATA_PRESENTATION],
  },
  {
    id: 'TanStack/Virtual',
    kind: 'node',
    parent: [N.TAN_STACK],
    groups: [G.DATA_PRESENTATION],
  },

  {
    id: 'Apollo',
    kind: 'node',
    parent: [N.GRAPHQL],
    relations: [N.REACT, N.REACT_NATIVE, N.FASTIFY],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: 'Relay',
    kind: 'node',
    parent: [N.REACT],
    relations: [N.GRAPHQL],
    groups: [G.API_INTEGRATIONS],
    legacy: true,
  },
  {
    id: 'Axios',
    kind: 'node',
    parent: [N.REST],
    relations: [N.REACT, N.REACT_NATIVE, N.BACKBONE, N.ANGULAR_JS, N.ELECTRON, N.SOLID_JS],
    groups: [G.API_INTEGRATIONS],
    legacy: true,
  },

  // ── Build tools ──
  {
    id: N.BABEL,
    title: 'Babel',
    kind: 'node',
    size: 12,
    area: [A.WEB, A.MOBILE, A.BACK_END],
    parent: [N.WEBPACK, N.VITE, N.EXPRESS],
    relations: [N.REACT, N.WEBPACK, N.VITE, N.ANGULAR_JS, N.NODE_JS, N.JEST],
    groups: [G.BUILD_TOOLS],
    legacy: true,
  },
  {
    id: 'Turbopack',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [N.NEXT_JS],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: 'Gulp',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [N.ANGULAR_JS, N.BACKBONE],
    groups: [G.BUILD_TOOLS],
    legacy: true,
  },
  {
    id: 'Grunt',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [N.BACKBONE, N.ANGULAR_JS, N.EXT_JS],
    groups: [G.BUILD_TOOLS],
    legacy: true,
  },
  {
    id: 'RequireJS',
    kind: 'node',
    size: 12,
    area: [A.WEB],
    parent: [A.WEB],
    groups: [G.BUILD_TOOLS],
    legacy: true,
  },
  {
    id: 'TSC',
    kind: 'node',
    size: 12,
    area: [A.WEB, A.MOBILE],
    parent: [N.REACT, N.REACT_NATIVE, N.ELECTRON],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: 'Metro',
    kind: 'node',
    area: [A.MOBILE],
    parent: [N.REACT_NATIVE],
    groups: [G.BUILD_TOOLS],
  },
  {
    id: 'ESBuild',
    kind: 'node',
    area: [A.WEB],
    relations: [N.TS, N.VITE, N.BABEL],
    groups: [G.BUILD_TOOLS],
  },

  // ── Performance (Rollup/Bundle Analyzer nest under their bundler) ──
  { id: 'SEO', kind: 'node', area: [A.WEB], parent: [N.UX], groups: [G.PERFORMANCE] },
  {
    id: 'Lighthouse',
    kind: 'node',
    area: [A.WEB],
    parent: [N.UX, N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  { id: 'Lazy Loading', kind: 'node', area: [A.WEB], parent: [N.UX], groups: [G.PERFORMANCE] },
  {
    id: 'Jmeter',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'Performance Profile',
    kind: 'node',
    area: [A.WEB, A.DESKTOP],
    parent: [A.WEB, A.DESKTOP],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'V8 Profiler',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.BACK_END],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'React DevTools',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.BACK_END],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'Chrome CPU Profiler',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'Vitals',
    title: 'Vitals (LCP, INP, CLS)',
    kind: 'node',
    area: [A.WEB],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'Rollup Plugin Visualizer',
    kind: 'node',
    parent: [N.PROFILING, N.VITE],
    groups: [G.PERFORMANCE],
  },
  {
    id: 'Webpack Bundle Analyzer',
    kind: 'node',
    parent: [N.PROFILING, N.WEBPACK],
    groups: [G.PERFORMANCE],
    legacy: true,
  },
  {
    id: 'Flipper',
    kind: 'node',
    area: [A.MOBILE],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
    legacy: true,
  },
  {
    id: 'YSlow',
    kind: 'node',
    area: [A.WEB],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
    legacy: true,
  },
  {
    id: 'Google Page Speed',
    kind: 'node',
    area: [A.WEB],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
    legacy: true,
  },
  {
    id: 'Chrome Audit',
    kind: 'node',
    area: [A.WEB],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
    legacy: true,
  },
  {
    id: 'Firebug',
    kind: 'node',
    area: [A.WEB],
    parent: [N.PROFILING],
    groups: [G.PERFORMANCE],
    legacy: true,
  },

  // ── Database (PostGIS etc. nest under PostgreSQL; mongos under MongoDB) ──
  {
    id: 'SQLite',
    kind: 'node',
    area: [A.MOBILE],
    parent: [N.ELECTRON],
    groups: [G.DATABASE],
  },
  {
    id: 'IndexedDB',
    kind: 'node',
    area: [A.WEB, A.DESKTOP],
    parent: [N.REACT, N.NEXT_JS, N.ELECTRON],
    groups: [G.DATABASE],
  },
  { id: 'RxDB', kind: 'node', area: [A.WEB], parent: [N.REACT], groups: [G.DATABASE] },
  {
    id: 'ElectricSQL',
    kind: 'node',
    area: [A.DESKTOP],
    parent: [N.ELECTRON],
    groups: [G.DATABASE],
  },
  {
    id: 'Cassandra',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.TOTAL_JS, N.YII2],
    groups: [G.DATABASE],
  },
  {
    id: 'MySQL',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.EXPRESS, N.YII2],
    groups: [G.DATABASE],
  },
  { id: 'mongos', kind: 'node', parent: [N.MONGO] },
  { id: 'PostGIS', kind: 'node', parent: [N.POSTGRES] },
  { id: 'uuid-ossp', kind: 'node', parent: [N.POSTGRES] },
  { id: 'pgvector', kind: 'node', parent: [N.POSTGRES] },
  { id: 'TimescaleDB', kind: 'node', parent: [N.POSTGRES] },
  { id: 'Neo4j', kind: 'node', area: [A.BACK_END], parent: [N.NEST_JS], groups: [G.DATABASE] },
  { id: 'CouchBase', kind: 'node', area: [A.BACK_END], parent: [N.EXPRESS], groups: [G.DATABASE] },
  { id: 'MariaDB', kind: 'node', area: [A.BACK_END], parent: [N.EXPRESS], groups: [G.DATABASE] },
  {
    id: 'Redis',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.EXPRESS, N.NEST_JS],
    groups: [G.DATABASE],
  },

  {
    id: N.POSTGRES,
    title: 'PostgreSQL',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.NEST_JS, N.FASTIFY],
    groups: [G.DATABASE],
  },
  {
    id: N.MONGO,
    title: 'MongoDB',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.EXPRESS],
    groups: [G.DATABASE],
  },
  // ── CI/CD ──
  {
    id: N.JENKINS,
    title: 'Jenkins',
    kind: 'node',
    area: [A.BACK_END, A.DESKTOP, A.MOBILE, A.WEB],
    parent: [N.REACT, N.YII2, N.EXPRESS, N.REACT_NATIVE, N.ANGULAR_JS],
    groups: [G.CI_CD],
  },
  { id: 'CircleCI', kind: 'node', area: [A.MOBILE], parent: [N.REACT_NATIVE], groups: [G.CI_CD] },
  {
    id: 'GitLab CI',
    kind: 'node',
    area: [A.MOBILE, A.WEB],
    parent: [N.EXPRESS, N.NEST_JS, N.REACT, N.REACT_NATIVE, N.ANGULAR_JS],
    groups: [G.CI_CD],
  },
  {
    id: 'GitHub Actions',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [N.REACT, N.FASTIFY, N.EXPRESS, N.ELECTRON],
    groups: [G.CI_CD],
  },
  {
    id: N.BUILD_BOT,
    title: 'buildBot',
    kind: 'node',
    area: [A.DESKTOP],
    parent: [N.REACT, N.ELECTRON],
    groups: [G.CI_CD],
  },

  // ── Storage ──
  { id: 'AWS S3', kind: 'node', area: [A.BACK_END], parent: [N.NEST_JS], groups: [G.STORAGE] },
  {
    id: 'Cloudflare R2',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.NEST_JS],
    groups: [G.STORAGE],
  },
  { id: 'MinIO', kind: 'node', area: [A.BACK_END], parent: [N.NEST_JS], groups: [G.STORAGE] },
  {
    id: 'Google Cloud Storage',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.EXPRESS],
    groups: [G.STORAGE],
  },
  {
    id: 'Async-storage',
    kind: 'node',
    area: [A.MOBILE],
    parent: [N.REACT_NATIVE],
    groups: [G.STORAGE],
  },
  { id: 'Keychain', kind: 'node', area: [A.MOBILE], parent: [N.REACT_NATIVE], groups: [G.STORAGE] },
  { id: 'Keystore', kind: 'node', area: [A.MOBILE], parent: [N.REACT_NATIVE], groups: [G.STORAGE] },
  {
    id: 'fs',
    kind: 'node',
    area: [A.MOBILE, A.BACK_END],
    parent: [N.NODE_JS, N.REACT_NATIVE],
    groups: [G.STORAGE],
  },
  {
    id: 'localStorage',
    kind: 'node',
    area: [A.WEB],
    parent: [N.REACT, N.ANGULAR_JS, N.BACKBONE, N.JQUERY, N.NEXT_JS],
    groups: [G.STORAGE],
  },
  { id: 'sessionStorage', kind: 'node', area: [A.WEB], parent: [N.REACT], groups: [G.STORAGE] },
  {
    id: 'electron-store',
    kind: 'node',
    area: [A.DESKTOP],
    parent: [N.ELECTRON],
    groups: [G.STORAGE],
  },

  // ── Testing ──
  {
    id: N.TEST,
    title: 'Testing',
    kind: 'node',
    parent: [A.DESKTOP, A.MOBILE, A.WEB, A.BACK_END],
    groups: [G.TEST_UNIT, G.TEST_E2E],
  },
  {
    id: N.JEST,
    title: 'Jest',
    kind: 'node',
    area: [A.DESKTOP, A.MOBILE, A.WEB, A.BACK_END],
    parent: [N.TEST],
    relations: [N.REACT, N.ELECTRON, N.NEXT_JS, N.REACT_NATIVE],
    groups: [G.TEST_UNIT],
  },

  {
    id: N.VITEST,
    title: 'Vitest',
    kind: 'node',
    area: [A.DESKTOP, A.MOBILE, A.WEB, A.BACK_END],
    parent: [N.TEST],
    relations: [N.REACT, N.ELECTRON, N.NEST_JS],
    groups: [G.TEST_UNIT],
  },
  {
    id: 'Mocha',
    kind: 'node',
    area: [A.WEB, A.BACK_END],
    parent: [N.TEST],
    relations: [N.BACKBONE, N.ANGULAR_JS, N.EXTJS],
    groups: [G.TEST_UNIT],
    legacy: true,
  },
  {
    id: 'Chai',
    kind: 'node',
    area: [A.WEB, A.DESKTOP, A.MOBILE, A.BACK_END],
    parent: [N.TEST],
    relations: [N.ANGULAR_JS, N.EXTJS, N.BACKBONE, N.ELECTRON, N.EXPRESS],
    groups: [G.TEST_UNIT],
    legacy: true,
  },
  {
    id: 'Jasmine',
    kind: 'node',
    area: [A.WEB, A.DESKTOP],
    parent: [N.TEST],
    relations: [N.ANGULAR_JS, N.EXTJS, N.BACKBONE, N.ELECTRON],
    groups: [G.TEST_UNIT],
    legacy: true,
  },
  {
    id: 'Cypress',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP],
    parent: [N.TEST],
    relations: [N.ELECTRON, N.REACT_NATIVE, N.REACT],
    groups: [G.TEST_E2E],
  },
  {
    id: N.PLAYWRIGHT,
    title: 'Playwright',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP],
    parent: [N.TEST],
    relations: [N.ELECTRON, N.REACT_NATIVE, N.REACT],
    groups: [G.TEST_E2E],
  },
  {
    id: 'Selenium',
    kind: 'node',
    area: [A.WEB],
    parent: [N.TEST],
    relations: [N.ANGULAR_JS, N.EXTJS, N.BACKBONE, N.ELECTRON],
    groups: [G.TEST_E2E],
    legacy: true,
  },
  {
    id: N.MSW,
    title: 'MSW',
    kind: 'node',
    area: [A.WEB, A.MOBILE],
    parent: [N.TEST],
    relations: [N.REACT, N.REACT_NATIVE, N.ELECTRON, N.VITEST, N.PLAYWRIGHT],
    groups: [G.TEST_UNIT, G.DATA_FETCHING],
  },
  {
    id: 'testing-library',
    kind: 'node',
    area: [A.WEB, A.MOBILE],
    parent: [N.TEST],
    groups: [G.TEST_UNIT],
  },
  {
    id: 'RNTL',
    title: 'React Native Testing Library',
    kind: 'node',
    area: [A.MOBILE],
    parent: [A.MOBILE],
    groups: [G.TEST_UNIT],
  },

  // ── Security / Validation / ORM ──
  {
    id: 'Zod',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [N.REACT, N.ELECTRON, N.REACT_NATIVE, N.NEST_JS],
    groups: [G.VALIDATION],
  },
  {
    id: 'Yup',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [N.REACT, N.ELECTRON, N.REACT_NATIVE, N.EXPRESS],
    groups: [G.VALIDATION],
  },
  { id: 'Prisma', kind: 'node', area: [A.BACK_END], parent: [N.NEST_JS], groups: [G.ORM] },
  {
    id: 'CSRF middleware',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.NODE_JS],
    groups: [G.SECURITY],
  },
  {
    id: 'CORS',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [N.REACT, N.ELECTRON, N.REACT_NATIVE, N.EXPRESS, N.BACKBONE, N.ANGULAR_JS, N.YII2],
    groups: [G.SECURITY],
  },
  {
    id: 'CSP',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.DESKTOP, A.BACK_END],
    parent: [N.UX],
    groups: [G.SECURITY],
  },
  {
    id: 'XSS',
    kind: 'node',
    area: [A.WEB],
    parent: [N.REACT, N.ELECTRON, N.REACT_NATIVE, N.EXPRESS, N.BACKBONE, N.ANGULAR_JS, N.YII2],
    groups: [G.SECURITY],
  },
  { id: 'Helmet', kind: 'node', area: [A.BACK_END], parent: [N.NODE_JS], groups: [G.SECURITY] },

  // ── API ──
  {
    id: N.REST,
    title: 'REST',
    kind: 'node',
    area: [A.BACK_END, A.MOBILE, A.WEB],
    parent: [N.NODE_JS, N.PHP],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: 'RESTful',
    kind: 'node',
    area: [A.BACK_END],
    parent: [A.BACK_END],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: N.GRAPHQL,
    title: 'GraphQL',
    kind: 'node',
    area: [A.BACK_END, A.MOBILE, A.WEB],
    parent: [N.REACT, N.EXPRESS],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: N.GRPC,
    title: 'gRPC',
    kind: 'node',
    area: [A.BACK_END, A.WEB],
    parent: [N.REACT, N.FASTIFY],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: N.RPC,
    title: 'RPC',
    kind: 'node',
    area: [A.BACK_END],
    parent: [N.REACT, N.ELECTRON, N.EXPRESS],
    groups: [G.API_INTEGRATIONS],
  },
  {
    id: N.SOAP,
    title: 'SOAP',
    kind: 'node',
    area: [A.WEB],
    parent: [N.ANGULAR_JS],
    groups: [G.API_INTEGRATIONS],
    legacy: true,
  },
  {
    id: N.WS,
    title: 'WebSockets',
    kind: 'node',
    parent: [N.REACT, N.ELECTRON, N.NEXT_JS, N.REACT_NATIVE, N.ANGULAR_JS],
    groups: [G.DATA_STREAM, G.DATA_FETCHING],
    legacy: true,
  },
  {
    id: 'Signal.io',
    kind: 'node',
    area: [A.MOBILE],
    parent: [N.WS],
    groups: [G.DATA_STREAM],
    legacy: true,
  },
  {
    id: 'Socket.io',
    kind: 'node',
    area: [A.WEB, A.BACK_END],
    parent: [N.WS],
    groups: [G.DATA_STREAM, G.DATA_FETCHING],
  },
  {
    id: 'SocketCluster',
    kind: 'node',
    area: [A.WEB, A.MOBILE, A.BACK_END],
    parent: [N.WS],
    groups: [G.DATA_STREAM, G.DATA_FETCHING],
  },
  {
    id: 'Server-Sent Events',
    kind: 'node',
    area: [A.WEB],
    parent: [N.WS],
    groups: [G.DATA_STREAM],
  },

  // ── Libs ──
  { id: 'D3', kind: 'node', size: 12, area: [A.WEB], parent: [A.WEB] },
]
